### ISSUE TITLE
Kamodo import fails with Python 3.12

### ISSUE THREAD

**Issue by sapols** [heliophysicsPy/pyhc-core#9]
It succeeds just fine for Python 3.9–3.11, but with 3.12 we get this error:

```
Run python -c "import hapiclient"
  python -c "import hapiclient"
  python -c "import kamodo"
  python -c "import plasmapy"
  python -c "import pysat"
  python -c "import pyspedas"
  python -c "import spacepy"
  python -c "import sunpy"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/kamodo/__init__.py", line 7, in <module>
    from kamodo.kamodo import *
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/kamodo/kamodo.py", line 45, in <module>
    from plotting import get_ranges
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/kamodo/plotting.py", line 13, in <module>
    from util import arg_to_latex, beautify_latex, cast_0_dim, get_defaults
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/kamodo/util.py", line 21, in <module>
    from numpy.distutils.exec_command import exec_command
ModuleNotFoundError: No module named 'numpy.distutils'
Error: Process completed with exit code 1.
```

The culprit is `ModuleNotFoundError: No module named 'numpy.distutils'`.

**Comment by sapols** [comment]
I tried it again just now and `pip install pyhc-core` actually did pass with Python 3.12.11 (so did `pip install pyhc-core[tests]`).

I see Kamodo [bumped their Python version to `>=3.10` in September](https://github.com/nasa/Kamodo/commit/893fcf5fd116827570272641ad49fa9437e0ce75). Maybe that fixed it.

It failed for Python 3.13 though, although it wasn't Kamodo's fault; it seems `numpy<2` will not be supported in Python>=3.13. So `pip install pyhc-core` fails in Python 3.13 because it fails to install `numpy<2`.
